version: '3.8'

services:
  web:
    container_name: web
    image: nginx
    networks:
     - proxy-net
    environment:
      VIRTUAL_HOST: aigram.jp
      LETSENCRYPT_HOST: aigram.jp
      LETSENCRYPT_EMAIL: ban@aigram.jp
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  proxy-net:
    name: proxy-net
    driver: bridge
    external: true